/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ForSellersRouteImport } from './routes/for-sellers'
import { Route as ForRepositioningInvestorsRouteImport } from './routes/for-repositioning-investors'
import { Route as ForOwnerUsersRouteImport } from './routes/for-owner-users'
import { Route as ForInvestorsRouteImport } from './routes/for-investors'
import { Route as ForBuyersRouteImport } from './routes/for-buyers'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsPolkRouteImport } from './routes/markets.polk'
import { Route as MarketsPinellasRouteImport } from './routes/markets.pinellas'
import { Route as MarketsPascoRouteImport } from './routes/markets.pasco'
import { Route as MarketsHillsboroughRouteImport } from './routes/markets.hillsborough'
import { Route as MarketsHernandoRouteImport } from './routes/markets.hernando'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSellersRoute = ForSellersRouteImport.update({
  id: '/for-sellers',
  path: '/for-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRepositioningInvestorsRoute =
  ForRepositioningInvestorsRouteImport.update({
    id: '/for-repositioning-investors',
    path: '/for-repositioning-investors',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForOwnerUsersRoute = ForOwnerUsersRouteImport.update({
  id: '/for-owner-users',
  path: '/for-owner-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ForInvestorsRoute = ForInvestorsRouteImport.update({
  id: '/for-investors',
  path: '/for-investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBuyersRoute = ForBuyersRouteImport.update({
  id: '/for-buyers',
  path: '/for-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsPolkRoute = MarketsPolkRouteImport.update({
  id: '/markets/polk',
  path: '/markets/polk',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsPinellasRoute = MarketsPinellasRouteImport.update({
  id: '/markets/pinellas',
  path: '/markets/pinellas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsPascoRoute = MarketsPascoRouteImport.update({
  id: '/markets/pasco',
  path: '/markets/pasco',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsHillsboroughRoute = MarketsHillsboroughRouteImport.update({
  id: '/markets/hillsborough',
  path: '/markets/hillsborough',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsHernandoRoute = MarketsHernandoRouteImport.update({
  id: '/markets/hernando',
  path: '/markets/hernando',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-investors': typeof ForInvestorsRoute
  '/for-owner-users': typeof ForOwnerUsersRoute
  '/for-repositioning-investors': typeof ForRepositioningInvestorsRoute
  '/for-sellers': typeof ForSellersRoute
  '/listings': typeof ListingsRoute
  '/market': typeof MarketRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/markets/hernando': typeof MarketsHernandoRoute
  '/markets/hillsborough': typeof MarketsHillsboroughRoute
  '/markets/pasco': typeof MarketsPascoRoute
  '/markets/pinellas': typeof MarketsPinellasRoute
  '/markets/polk': typeof MarketsPolkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-investors': typeof ForInvestorsRoute
  '/for-owner-users': typeof ForOwnerUsersRoute
  '/for-repositioning-investors': typeof ForRepositioningInvestorsRoute
  '/for-sellers': typeof ForSellersRoute
  '/listings': typeof ListingsRoute
  '/market': typeof MarketRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/markets/hernando': typeof MarketsHernandoRoute
  '/markets/hillsborough': typeof MarketsHillsboroughRoute
  '/markets/pasco': typeof MarketsPascoRoute
  '/markets/pinellas': typeof MarketsPinellasRoute
  '/markets/polk': typeof MarketsPolkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-investors': typeof ForInvestorsRoute
  '/for-owner-users': typeof ForOwnerUsersRoute
  '/for-repositioning-investors': typeof ForRepositioningInvestorsRoute
  '/for-sellers': typeof ForSellersRoute
  '/listings': typeof ListingsRoute
  '/market': typeof MarketRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/markets/hernando': typeof MarketsHernandoRoute
  '/markets/hillsborough': typeof MarketsHillsboroughRoute
  '/markets/pasco': typeof MarketsPascoRoute
  '/markets/pinellas': typeof MarketsPinellasRoute
  '/markets/polk': typeof MarketsPolkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/for-buyers'
    | '/for-investors'
    | '/for-owner-users'
    | '/for-repositioning-investors'
    | '/for-sellers'
    | '/listings'
    | '/market'
    | '/services'
    | '/sitemap.xml'
    | '/markets/hernando'
    | '/markets/hillsborough'
    | '/markets/pasco'
    | '/markets/pinellas'
    | '/markets/polk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/for-buyers'
    | '/for-investors'
    | '/for-owner-users'
    | '/for-repositioning-investors'
    | '/for-sellers'
    | '/listings'
    | '/market'
    | '/services'
    | '/sitemap.xml'
    | '/markets/hernando'
    | '/markets/hillsborough'
    | '/markets/pasco'
    | '/markets/pinellas'
    | '/markets/polk'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/for-buyers'
    | '/for-investors'
    | '/for-owner-users'
    | '/for-repositioning-investors'
    | '/for-sellers'
    | '/listings'
    | '/market'
    | '/services'
    | '/sitemap.xml'
    | '/markets/hernando'
    | '/markets/hillsborough'
    | '/markets/pasco'
    | '/markets/pinellas'
    | '/markets/polk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForBuyersRoute: typeof ForBuyersRoute
  ForInvestorsRoute: typeof ForInvestorsRoute
  ForOwnerUsersRoute: typeof ForOwnerUsersRoute
  ForRepositioningInvestorsRoute: typeof ForRepositioningInvestorsRoute
  ForSellersRoute: typeof ForSellersRoute
  ListingsRoute: typeof ListingsRoute
  MarketRoute: typeof MarketRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MarketsHernandoRoute: typeof MarketsHernandoRoute
  MarketsHillsboroughRoute: typeof MarketsHillsboroughRoute
  MarketsPascoRoute: typeof MarketsPascoRoute
  MarketsPinellasRoute: typeof MarketsPinellasRoute
  MarketsPolkRoute: typeof MarketsPolkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-sellers': {
      id: '/for-sellers'
      path: '/for-sellers'
      fullPath: '/for-sellers'
      preLoaderRoute: typeof ForSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-repositioning-investors': {
      id: '/for-repositioning-investors'
      path: '/for-repositioning-investors'
      fullPath: '/for-repositioning-investors'
      preLoaderRoute: typeof ForRepositioningInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-owner-users': {
      id: '/for-owner-users'
      path: '/for-owner-users'
      fullPath: '/for-owner-users'
      preLoaderRoute: typeof ForOwnerUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-investors': {
      id: '/for-investors'
      path: '/for-investors'
      fullPath: '/for-investors'
      preLoaderRoute: typeof ForInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-buyers': {
      id: '/for-buyers'
      path: '/for-buyers'
      fullPath: '/for-buyers'
      preLoaderRoute: typeof ForBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/polk': {
      id: '/markets/polk'
      path: '/markets/polk'
      fullPath: '/markets/polk'
      preLoaderRoute: typeof MarketsPolkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/pinellas': {
      id: '/markets/pinellas'
      path: '/markets/pinellas'
      fullPath: '/markets/pinellas'
      preLoaderRoute: typeof MarketsPinellasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/pasco': {
      id: '/markets/pasco'
      path: '/markets/pasco'
      fullPath: '/markets/pasco'
      preLoaderRoute: typeof MarketsPascoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/hillsborough': {
      id: '/markets/hillsborough'
      path: '/markets/hillsborough'
      fullPath: '/markets/hillsborough'
      preLoaderRoute: typeof MarketsHillsboroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/hernando': {
      id: '/markets/hernando'
      path: '/markets/hernando'
      fullPath: '/markets/hernando'
      preLoaderRoute: typeof MarketsHernandoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForBuyersRoute: ForBuyersRoute,
  ForInvestorsRoute: ForInvestorsRoute,
  ForOwnerUsersRoute: ForOwnerUsersRoute,
  ForRepositioningInvestorsRoute: ForRepositioningInvestorsRoute,
  ForSellersRoute: ForSellersRoute,
  ListingsRoute: ListingsRoute,
  MarketRoute: MarketRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MarketsHernandoRoute: MarketsHernandoRoute,
  MarketsHillsboroughRoute: MarketsHillsboroughRoute,
  MarketsPascoRoute: MarketsPascoRoute,
  MarketsPinellasRoute: MarketsPinellasRoute,
  MarketsPolkRoute: MarketsPolkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}